// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cga_generate_chromosome
NumericVector cga_generate_chromosome(NumericVector prob_vec);
RcppExport SEXP eive_cga_generate_chromosome(SEXP prob_vecSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type prob_vec(prob_vecSEXP );
        NumericVector __result = cga_generate_chromosome(prob_vec);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cga
NumericVector cga(int chsize, int popsize, Function evalFunc);
RcppExport SEXP eive_cga(SEXP chsizeSEXP, SEXP popsizeSEXP, SEXP evalFuncSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type chsize(chsizeSEXP );
        Rcpp::traits::input_parameter< int >::type popsize(popsizeSEXP );
        Rcpp::traits::input_parameter< Function >::type evalFunc(evalFuncSEXP );
        NumericVector __result = cga(chsize, popsize, evalFunc);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
